### ISSUE TITLE
Invalid or incomplete example data for CONTACT message

### ISSUE THREAD

**Issue by JanikCodes** [MESE-Core/SEDAP-Express#3]
I think there is an issue in the documentation sample data for the message type CONTACT.
I believe sample 2 is not complete because it ends with NL which probably means New Line.

Besides that the pitch value is a O and not a 0. 

And maybe it's another issue in sample 3 because the csv ends without the leading ;
is that intended and can that occure? Thanks!

**Comment by VolkerVoss** [comment]
Hello!

NL in the sample stands for Netherlands ... I changed that, so it should be more clearly.
The only "O" I found stands for the source, in this case optical/visual source. 

It's intended that you can cut of the message after the last used attribute.
